# Generated by Django 5.2.2 on 2025-06-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='app.post'),
        ),
    ]
