# Generated by Django 5.2.2 on 2025-07-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
