# Generated by Django 5.2.2 on 2025-07-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_postcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following_categories',
            field=models.ManyToManyField(blank=True, related_name='followers', to='app.postcategory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_games',
            field=models.ManyToManyField(blank=True, related_name='followers', to='app.game'),
        ),
    ]
