# Generated by Django 5.2.2 on 2025-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userprofile_following_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('vote', 'Post Vote'), ('comment', 'New Comment'), ('reply', 'New Reply'), ('follower', 'New Follower'), ('save', 'Post Save'), ('mention', 'Mention')], max_length=20),
        ),
    ]
